// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEYU-A2jRUkT_dwBmaoU1KJH8eEDoTljM',
    appId: '1:592643251317:web:274b9b7b4115ccd1d76c3c',
    messagingSenderId: '592643251317',
    projectId: 'yaluan',
    authDomain: 'yaluan.firebaseapp.com',
    storageBucket: 'yaluan.firebasestorage.app',
    measurementId: 'G-31J43EBC8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_yU4lGSE0rbhSMFRvZLf2i7NkUpBGrwo',
    appId: '1:592643251317:android:a24682f6ad1d9fecd76c3c',
    messagingSenderId: '592643251317',
    projectId: 'yaluan',
    storageBucket: 'yaluan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwLnMcMAwmOIpCHYLJngwpPkOXjHtDE8g',
    appId: '1:592643251317:ios:4acd261dc6f60dd5d76c3c',
    messagingSenderId: '592643251317',
    projectId: 'yaluan',
    storageBucket: 'yaluan.firebasestorage.app',
    iosBundleId: 'com.example.btth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwLnMcMAwmOIpCHYLJngwpPkOXjHtDE8g',
    appId: '1:592643251317:ios:4acd261dc6f60dd5d76c3c',
    messagingSenderId: '592643251317',
    projectId: 'yaluan',
    storageBucket: 'yaluan.firebasestorage.app',
    iosBundleId: 'com.example.btth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEYU-A2jRUkT_dwBmaoU1KJH8eEDoTljM',
    appId: '1:592643251317:web:07f900fa46bfcfcdd76c3c',
    messagingSenderId: '592643251317',
    projectId: 'yaluan',
    authDomain: 'yaluan.firebaseapp.com',
    storageBucket: 'yaluan.firebasestorage.app',
    measurementId: 'G-G6YRD1117Z',
  );

}